import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/header";
import Footer from "./components/layout/footer";
import ScrollProgressBar from "./components/ui/scroll-progress-bar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const notoSansJp = Noto_Sans_JP({
  subsets: ["latin"],
  weight: ["400", "700"],
  preload: false,
  variable: "--font-noto-sans-jp",
  display: "swap",
  fallback: ["Hiragino Sans", "Hiragino Kaku Gothic ProN", "sans-serif"],
});

export const metadata: Metadata = {
  title: "GOUKI mysite",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${notoSansJp.variable} antialiased min-h-dvh`}
      >
        <ScrollProgressBar />
        <header className="fixed top-0 left-0 right-0 md:text-3xl text-2xl font-sans font-extralight h-20 z-10 grid grid-cols-2 grid-rows-1 items-center bg-transparent">
          <Header />
        </header>
        <main className="">
          {children}
        </main>
        <footer className="bottom-0 right-0 left-0 z-20 fixed outline-2 outline-emerald-500 dark:outline-emerald-950 bg-white/50 dark:bg-emerald-950/50">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
